New field-based device insertion mechanism
t0bst4r/home-assistant-matter-hub pull request #197
Opened 2024-11-24 22:08 UTC by adrisg

2024-11-26 07:53 UTC, t0bst4r commented
I love that! ❤️ 

But can you move the switch (and the if-else) between text and UI one level up?
The `JsonEditor` component is a generic json editor. It doesn't know what its used for, but the Form Editor is specific for the bridge config. So moving it one level up (to the `BridgeConfigEditor` component) would be much more clean.

2024-11-26 13:14 UTC, adrisg commented
You have already made all the changes I recommended.

2024-11-26 13:23 UTC, t0bst4r requested changes

2024-11-26 13:23 UTC, t0bst4r commented on packages/frontend/src/components/bridge/BridgeConfigEditor.tsx
> +  const handdleChangeEditionType = () => {
typo in the name - i'd also name it `toggle`

2024-11-26 13:23 UTC, t0bst4r commented on packages/frontend/src/components/bridge/BridgeConfigEditor.tsx
> +        : EditionModeType.FIELDS_EDITOR,
Sorry, but somehow `EditionModeType` sounds kinda weird. Let's call it `BridgeEditorMode`.

2024-11-26 13:23 UTC, t0bst4r commented on packages/frontend/src/components/bridge/BridgeConfigEditor.tsx
> +    <Box position="relative">
instead of absolute positioning, you can make the box `display="flex"` and `justifyContent="space-between"`

2024-11-26 13:23 UTC, t0bst4r commented on packages/frontend/src/components/fields-editor/FieldsEditor.tsx
> +  }, [fieldValues, value, onChange]);
i'd call `onChange` in `handleOnChange` and would remove that whole `useEffect` here.

2024-11-26 13:23 UTC, t0bst4r commented on packages/frontend/src/components/fields-editor/FieldsEditor.tsx
> +            <Grid2 size={12}>
what's the point of using `Grid` when all children have full size? If its only about `rowSpacing`, use `Stack` instead.

2024-11-26 13:23 UTC, t0bst4r commented on packages/frontend/src/components/fields-editor/FieldsEditor.tsx
> +  const handdleOnAddField = () => {
typo in handle

2024-11-26 13:23 UTC, t0bst4r commented on packages/frontend/src/components/fields-editor/FieldsEditor.tsx
> +  const handdleChange = (
typo in handle

2024-11-26 13:23 UTC, t0bst4r commented on packages/frontend/src/components/fields-editor/FieldsEditor.tsx
> +export default FieldsEditor;
i'd split that whole file into multiple files. just to improve readability.
maybe also rename the components for better namings.

2024-11-26 13:28 UTC, adrisg commented
Ok I'll start to resolve all these comments :)

2024-11-26 14:45 UTC, adrisg commented
I've already made all the changes you suggested. I've also changed the names of some components as you requested. You can obviously rename them as you wish.

2024-11-27 15:29 UTC, t0bst4r commented
i am doing a release today, without merging this, because i'd like to do some more changes to it, after merging. 
unfortunately i dont have any more time today. I'll probably do it tomorrow.

2024-11-27 15:41 UTC, adrisg commented
Don't worry, do you want me to resolve conflicts?

2024-11-27 15:57 UTC, t0bst4r commented
Yes, that would be great!

Just fyi what will be changed after merge tomorrow:

I’ll rename some variables and components and then make the whole configuration either json or form - not only the filter.
So input/output will be the whole bridge configuration instead of only „editable bridge config“.

2024-11-28 13:26 UTC, adrisg commented
> ¡¡Gracias!! Y tu código no estaba tan mal 🙂
> 
> ¿Ya viste tu logo? ❤️

Yes, I saw it and I loved it! :) Well. 
My code isn't bad, but there's definitely room for improvement, haha!

2024-11-28 13:59 UTC, t0bst4r commented
After half a day of refactoring i noticed that i am building a form component which accepts json schema as configuration.
Then i noticed there's a library for that 😀

2024-11-28 14:04 UTC, merged